In [ ]:
!pip install lxml[html_clean]
!apt-get update
!apt-get install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium newspaper3k nltk bs4 requests scikit-learn gensim

Requirement already satisfied: lxml[html_clean] in /usr/local/lib/python3.12/dist-packages (5.4.0)
Requirement already satisfied: lxml_html_clean in /usr/local/lib/python3.12/dist-packages (from lxml[html_clean]) (0.4.2)
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
cp: '/usr/lib/chromium-browser/chromedriver' and '/usr/bin/chromedriver' are the same file
Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.35.0)
Requirement already satisfied: newspaper3k in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: bs4 in /usr/local/lib/python3.12/dist-packages (0.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.3.3)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Requirement already satisfied: trio~=0.30.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.6.15 in /usr/local/lib/python3.12/dist-packages (from selenium) (2025.8.3)
Requirement already satisfied: typing_extensions~=4.14.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.14.1)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (1.3.0)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.4.0)
Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.11)
Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.3.0)
Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.0.post1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.7)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (2.1.0)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.19.1)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('popular')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
!pip install xlsxwriter

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.5)

In [ ]:
# Import các thư viện cần thiết cho quá trình scraping, xử lý dữ liệu, và xuất file
import os
import re
import time
from datetime import datetime
import random
import json
import requests
import tempfile
import atexit
from tqdm import tqdm
import pandas as pd
from bs4 import BeautifulSoup
from newspaper import Article
from selenium import webdriver  # Thư viện để tự động hóa trình duyệt, hỗ trợ scraping động
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException, WebDriverException
from selenium.webdriver.common.keys import Keys
from google.colab import files
from urllib.parse import urljoin

# ***TIN NHANH CHUNG KHOAN***

In [ ]:
import requests, re, unicodedata
from openpyxl import load_workbook
from openpyxl.styles import Font

# 1. Bản đồ mã → tên tiếng Việt & Anh
company_map = {
    "mã VNM": ("CTCP Sữa Việt Nam", "Công ty cổ phần Sữa Việt Nam"),
    "mã ANV": ("Công ty cổ phần Nam Việt", "CTCP Nam Việt"),
    "mã BMP": ("Công ty cổ phần Nhựa Bình Minh", "CTCP Nhựa Bình Minh"),
    "mã BSI": ("Công ty Cổ phần Chứng khoán BIDV", "CTCP Chứng khoán BIDV"),
    "mã CMG": ("CMC Corp", "CTCP Tập đoàn Công nghệ CMC "),
    "mã CTD": ("Công ty Cổ phần Xây dựng Coteccons", "CTCP xây dựng Coteccons","Mã chứng khoán: CTD - HOSE"),
    "mã DBC": ("Công ty Cổ phần Tập đoàn Dabaco Việt Nam", "CTCP Tập đoàn Dabaco Việt Nam","DBC – sàn HOSE","Mã chứng khoán: DBC - HOSE"),
    "mã DIG": ("Tổng công ty cổ phần Đầu tư Phát triển Xây dựng", "Tổng CTCP Đầu tư phát triển xây dựng","DIC Corp"),
    "mã FPT": ("FPT Corporation", "Tập đoàn FPT","CTCP FPT"),
    "mã GAS": ("Tổng công ty Khí Việt Nam", "PV GAS","Tổng công ty Khí Việt Nam – CTCP","Tổng CTCP Gas Petrolimex"),
    "mã GMD": ("Công ty cổ phần Gemadept", "CTCP Gemadept"),
    "mã HCM": ("CTCP Chứng khoán TP. HCM", "Công ty cổ phần Chứng khoán TP. HCM","Chứng khoán HSC"),
    "mã HDG": ("CTCP Tập đoàn Hà Đô", "Công ty Cổ phần Tập đoàn Hà Đô"),
    "mã HPG": ("CTCP Tập đoàn Hòa Phát", "Công ty Cổ phần Tập đoàn Hòa Phát"),
    "mã HSG": ("Tập đoàn Hoa Sen", "CTCP Tập đoàn Hoa Sen"),
    "mã IMP": ("Công ty Cổ phần Dược phẩm Imexpharm", "CTCP Dược phẩm Imexpharm"),
    "mã KBC": ("Tổng CTCP Phát triển Đô thị Kinh Bắc", "Phát triển Đô thị Kinh Bắc"),
    "mã KDH": ("CTCP Khang Điền", "Khang Điền"),
    "mã MBB": ("Ngân hàng TMCP Quân đội", "Ngân hàng thương mại cổ phần Quân Đội","MBBank"),
    "mã NKG": ("CTCP Thép Nam Kim", "Nam Kim"),
    "mã PDR": ("CTCP Phát triển Bất động sản Phát Đạt", "Công ty cổ phần Phát triển Bất động sản Phát Đạt"),
    "mã PNJ": ("CTCP Vàng bạc đá quý Phú Nhuận", "Công ty cổ phần Vàng bạc đá quý Phú Nhuận"),
    "mã PTB": ("Công ty Cổ phần Phú Tài", "CTCP Phú Tài"),
    "mã REE": ("Cơ điện lạnh (REE)", "CTCP Cơ điện lạnh","Công ty cổ phần Cơ điện lạnh"),
    "mã SSI": ("CTCP Chứng khoán SSI", "Công ty cổ phần Chứng khoán SSI"),
    "mã VCB": ("Ngân hàng TMCP Ngoại thương Việt Nam", "Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam"),
    "mã VIX": ("CTCP Chứng khoán VIX", "Công ty cổ phần Chứng khoán VIX"),
    "mã VND": ("VNDirect", "CTCP Chứng khoán VNDirect"),
    "mã VSC": ("Viconship", "CTCP Container Việt Nam","Công ty Cổ phần Container Việt Nam"),
    "mã TLG": ("Tập đoàn Thiên Long",)
}

# 2. Tạo từ khóa: mã + các tên tiếng Việt
ticker_keywords = {
    ticker: [ticker.lower()] + [name.lower() for name in names]
    for ticker, names in company_map.items()
}

# 3. Hàm làm sạch văn bản
def clean_text(txt):
    if not txt:
        return ""
    reps = {'\u200b':'','\u00a0':' ', '\u2013':'-','\u2014':'--',
            '\u2018':"'",'\u2019':"'", '\u201c':'"','\u201d':'"',
            '\u2026':'...'}
    for a, b in reps.items():
        txt = txt.replace(a, b)
    return re.sub(r'[\x00-\x1f\x7f-\x9f]', '', txt).strip()

# 4. Lấy link từ sitemap theo ngày
def get_sitemap_urls(url, from_dt, to_dt):
    r = requests.get(url, headers={"User-Agent":"Mozilla/5.0"})
    soup = BeautifulSoup(r.text, 'xml')
    out = []
    for u in soup.find_all('url'):
        lm = u.find('lastmod')
        if not lm:
            continue
        try:
            dt = datetime.fromisoformat(lm.text).replace(tzinfo=None)
        except:
            continue
        if from_dt <= dt < to_dt:
            loc = u.find('loc').text.strip()
            out.append((loc, dt.strftime("%d/%m/%Y %H:%M")))
    return out

# 5. Crawl nội dung và xác định ticker
def fetch(link):
    r = requests.get(link, headers={"User-Agent":"Mozilla/5.0"}, timeout=15)
    soup = BeautifulSoup(r.text, "html.parser")
    # Lấy tiêu đề
    title_tag = soup.select_one("h1.article__header.cms-title")
    title = clean_text(title_tag.get_text(strip=True)) if title_tag else ""
    # Lấy tóm tắt và nội dung để kiểm tra mã
    sumpt = soup.select_one("div.article__sapo.cms-desc")
    body_div = soup.select_one("div.article__body.cms-body")
    summary = clean_text(sumpt.get_text(strip=True)) if sumpt else ""
    if body_div and body_div.find(["iframe","video","embed"]):
        return None
    paragraphs = body_div.find_all("p") if body_div else []
    body = "\n".join(clean_text(p.get_text(strip=True)) for p in paragraphs)
    if len(summary) + len(body) < 200:
        return None
    content = summary  # Chỉ lấy tóm tắt
    full_lower = (summary + " " + body).lower()  # Kiểm tra mã trong cả tóm tắt và nội dung

    found = {t: kws for t, kws in ticker_keywords.items()
             if any(k in full_lower for k in kws)}
    if not found:
        return None

    keywords = sum(found.values(), [])
    return {"title": title, "content": content, "tickers": list(found.keys()), "keywords": keywords}

# 6. In đậm các từ khóa trong Content
def apply_bold(ws, row, content, kws):
    cell = ws.cell(row=row, column=7)
    if not kws:
        cell.value = content
        return
    patt = "|".join(re.escape(k) for k in kws)
    out, last = [], 0
    for m in re.finditer(patt, content, re.IGNORECASE):
        out.append(content[last:m.start()])
        out.append(f"**{content[m.start():m.end()]}**")
        last = m.end()
    out.append(content[last:])
    cell.value = "".join(out)

# 7. Main
def main():
    base = "https://www.tinnhanhchungkhoan.vn/sitemaps/"
    maps = ["news-2025-6.xml", "news-2025-1.xml"]
    from_dt = datetime(2025,1,1)
    to_dt   = datetime(2025,6,30)
    rows = []

    for sm in maps:
        for link, dt in get_sitemap_urls(base+sm, from_dt, to_dt):
            res = fetch(link)
            if not res:
                continue
            tickers = res["tickers"]
            kws = res["keywords"]
            rows.append({
                "Date": dt,
                "Link": link,
                "Tickers": ", ".join(tickers),
                "Tiêu Đề": res["title"],
                "Content": res["content"],
                "Keywords": ", ".join(kws)
            })
            print(f"✅ {dt} | {link} -> {rows[-1]['Tickers']} | {rows[-1]['Tiêu Đề']}")

    if not rows:
        print("❌ Không có bài viết phù hợp.")
        return

    df = pd.DataFrame(rows)
    fn = "multi_tickers_combined.xlsx"
    df.to_excel(fn, index=False, engine="openpyxl")

    wb = load_workbook(fn)
    ws = wb.active
    widths = [15, 50, 20, 40, 60, 100, 30]  # Điều chỉnh chiều rộng cho cột Tiêu Đề
    for col, w in zip("ABCDEFG", widths):
        ws.column_dimensions[col].width = w

    for idx, r in enumerate(rows, start=2):
        apply_bold(ws, idx, r["Content"], r["Keywords"].split(", "))

    for cell in ws[1]: cell.font = Font(bold=True)
    wb.save(fn)
    print(f"🎉 Đã lưu {len(rows)} dòng vào '{fn}'")

if __name__ == "__main__":
    main()

✅ 29/06/2025 10:12 | https://www.tinnhanhchungkhoan.vn/ha-tang-tai-san-so-tai-viet-nam-tay-choi-lon-bat-dau-hanh-dong-post372062.html -> mã SSI | Hạ tầng tài sản số tại Việt Nam: "Tay chơi lớn" bắt đầu hành động
✅ 28/06/2025 10:27 | https://www.tinnhanhchungkhoan.vn/hai-an-hah-len-tieng-ve-moi-quan-he-hop-tac-voi-viconship-vsc-sau-khi-nhom-co-dong-nang-so-huu-len-1531-post372019.html -> mã VSC | Hải An (HAH) lên tiếng về mối quan hệ hợp tác với Viconship (VSC) sau khi nhóm cổ đông nâng sở hữu lên 15,31%
✅ 28/06/2025 10:24 | https://www.tinnhanhchungkhoan.vn/gemadept-gmd-sap-chi-hon-84038-ty-dong-de-tra-co-tuc-nam-2024-post372020.html -> mã GMD | Gemadept (GMD) sắp chi hơn 840,38 tỷ đồng để trả cổ tức năm 2024
✅ 27/06/2025 18:02 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-286-post372012.html -> mã GMD | Sự kiện chứng khoán đáng chú ý ngày 28/6
✅ 27/06/2025 15:00 | https://www.tinnhanhchungkhoan.vn/dhcd-phat-dat-pdr-chuyen-nhuong-80-du-an-thuan-an-1-cho-doi-tac-nhat-va-se-nhan-tien-trong-thang-92025-post371984.html -> mã PDR | ĐHCĐ Phát Đạt (PDR): Chuyển nhượng 80% dự án Thuận An 1 cho đối tác Nhật và sẽ nhận tiền trong tháng 9/2025
✅ 27/06/2025 11:28 | https://www.tinnhanhchungkhoan.vn/dhcd-f88-chot-tang-truong-du-no-43-doanh-thu-33-loi-nhuan-50-post371978.html -> mã MBB | ĐHCĐ F88 "chốt" tăng trưởng dư nợ 43%, doanh thu 33%, lợi nhuận 50%
✅ 27/06/2025 11:00 | https://www.tinnhanhchungkhoan.vn/hodeco-hdc-len-ke-hoach-trien-khai-hang-loat-cum-khu-cong-nghiep-post371961.html -> mã KBC | Hodeco (HDC) lên kế hoạch triển khai hàng loạt cụm khu công nghiệp
✅ 27/06/2025 09:42 | https://www.tinnhanhchungkhoan.vn/ton-vinh-doanh-nghiep-tieu-bieu-ve-esg-va-doi-moi-sang-tao-nam-2025-post371959.html -> mã VCB | Tôn vinh doanh nghiệp tiêu biểu về ESG và Đổi mới sáng tạo năm 2025
✅ 27/06/2025 08:00 | https://www.tinnhanhchungkhoan.vn/thi-truong-bien-dong-dau-la-chien-luoc-cho-nha-dau-tu-post371935.html -> mã VND | Thị trường biến động: Đâu là chiến lược cho nhà đầu tư?
✅ 27/06/2025 06:36 | https://www.tinnhanhchungkhoan.vn/ban-le-hoi-phuc-co-phieu-van-con-du-dia-tang-post371653.html -> mã PNJ | Bán lẻ hồi phục, cổ phiếu vẫn còn dư địa tăng
✅ 26/06/2025 17:56 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-276-post371938.html -> mã ANV, mã MBB | Cổ phiếu cần quan tâm ngày 27/6
✅ 26/06/2025 17:53 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-276-post371934.html -> mã VND | Sự kiện chứng khoán đáng chú ý ngày 27/6
✅ 26/06/2025 10:36 | https://www.tinnhanhchungkhoan.vn/chuan-bi-dau-tu-nhieu-du-an-nang-luong-hydrogen-post371899.html -> mã GAS | Chuẩn bị đầu tư nhiều dự án năng lượng hydrogen
✅ 26/06/2025 06:44 | https://www.tinnhanhchungkhoan.vn/don-doi-nhung-thuong-vu-ipo-bom-tan-post371648.html -> mã VND | Đón đợi những thương vụ IPO "bom tấn"
✅ 25/06/2025 17:44 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-266-post371864.html -> mã GMD, mã VSC | Cổ phiếu cần quan tâm ngày 26/6
✅ 25/06/2025 09:33 | https://www.tinnhanhchungkhoan.vn/cong-ty-con-cua-co-dien-lanh-ree-muon-ban-ra-2-trieu-co-phieu-saigonres-sgr-post371813.html -> mã REE | Công ty con của Cơ Điện Lạnh (REE) muốn bán ra 2 triệu cổ phiếu Saigonres (SGR)
✅ 24/06/2025 17:39 | https://www.tinnhanhchungkhoan.vn/dhcd-gemadept-gmd-ket-qua-kinh-doanh-nua-dau-nam-kha-quan-du-an-nam-dinh-vu-giai-doan-3-se-hoan-thanh-trong-quy-iv2025-post371784.html -> mã GMD | ĐHCĐ Gemadept (GMD): Kết quả kinh doanh nửa đầu năm khả quan, dự án Nam Đình Vũ - Giai đoạn 3 sẽ hoàn thành trong quý IV/2025
✅ 23/06/2025 17:50 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-256-post371738.html -> mã HPG | Sự kiện chứng khoán đáng chú ý ngày 25/6
✅ 23/06/2025 17:45 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-246-post371737.html -> mã HDG | Cổ phiếu cần quan tâm ngày 24/6
✅ 23/06/2025 15:43 | https://www.tinnhanhchungkhoan.vn/dabaco-viet-nam-dbc-gop-von-thanh-lap-cong-ty-chan-nuoi-tai-quang-tri-post371713.html -> mã DBC | Dabaco Việt Nam (DBC) góp vốn thành lập công ty chăn nuôi tại Quảng Trị
✅ 23/06/2025 09:59 | https://www.tinnhanhchungkhoan.vn/nang-hang-thi-truong-chung-khoan-co-hoi-don-song-dau-tu-ngoai-post371696.html -> mã KDH, mã MBB, mã PDR | Nâng hạng thị trường chứng khoán: Cơ hội đón sóng đầu tư ngoại
✅ 23/06/2025 06:41 | https://www.tinnhanhchungkhoan.vn/dong-tien-tap-trung-vao-bluechips-post371651.html -> mã HPG | Dòng tiền tập trung vào bluechips
✅ 22/06/2025 17:42 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-236-post371638.html -> mã CTD | Cổ phiếu cần quan tâm ngày 23/6
✅ 22/06/2025 08:03 | https://www.tinnhanhchungkhoan.vn/du-bao-loi-nhuan-doanh-nghiep-dau-khi-quy-ii-nhom-thuong-nguon-tich-cuc-post371664.html -> mã GAS | Dự báo lợi nhuận doanh nghiệp dầu khí quý II: Nhóm thượng nguồn tích cực
✅ 21/06/2025 18:04 | https://www.tinnhanhchungkhoan.vn/tri-tue-nhan-tao-la-chia-khoa-van-hanh-do-thi-hien-dai-post371637.html -> mã FPT | Trí tuệ nhân tạo là "chìa khóa" vận hành đô thị hiện đại
✅ 21/06/2025 10:55 | https://www.tinnhanhchungkhoan.vn/khong-con-la-cuoc-choi-rieng-le-viet-nam-chinh-thuc-co-lien-minh-ai-post371632.html -> mã FPT | Không còn là cuộc chơi riêng lẻ, Việt Nam chính thức có Liên minh AI
✅ 21/06/2025 09:00 | https://www.tinnhanhchungkhoan.vn/cau-noi-giua-doanh-nghiep-va-nha-dau-tu-post371216.html -> mã GMD, mã NKG, mã REE | Cầu nối giữa doanh nghiệp và nhà đầu tư
✅ 20/06/2025 19:32 | https://www.tinnhanhchungkhoan.vn/ra-mat-cua-hang-tai-chinh-theo-chuan-ngan-hang-f88-du-tinh-dieu-gi-post371620.html -> mã MBB | Ra mắt cửa hàng tài chính theo chuẩn ngân hàng, F88 dự tính điều gì?
✅ 20/06/2025 13:54 | https://www.tinnhanhchungkhoan.vn/dhcd-kosy-kos-don-luc-khac-phuc-kho-khan-muc-tieu-lai-118-ty-dong-trong-nam-2025-post371592.html -> mã MBB | ĐHCĐ Kosy (KOS): Dồn lực khắc phục khó khăn, mục tiêu lãi 118 tỷ đồng trong năm 2025
✅ 20/06/2025 10:20 | https://www.tinnhanhchungkhoan.vn/doanh-nghiep-niem-yet-xoay-truc-ir-post371210.html -> mã HPG | Doanh nghiệp niêm yết xoay trục IR
✅ 20/06/2025 06:54 | https://www.tinnhanhchungkhoan.vn/doanh-nghiep-dia-oc-dai-cat-tim-vang-post371247.html -> mã DIG, mã KDH | Doanh nghiệp địa ốc "đãi cát tìm vàng"
✅ 19/06/2025 19:58 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-206-post371551.html -> mã VND | Sự kiện chứng khoán đáng chú ý ngày 20/6
✅ 19/06/2025 17:42 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-206-post371548.html -> mã VNM | Cổ phiếu cần quan tâm ngày 20/6
✅ 19/06/2025 10:19 | https://www.tinnhanhchungkhoan.vn/minh-bach-thong-tin-tang-niem-tin-giam-rui-ro-post371207.html -> mã HDG, mã MBB | Minh bạch thông tin: Tăng niềm tin, giảm rủi ro
✅ 19/06/2025 08:44 | https://www.tinnhanhchungkhoan.vn/nhan-dien-diem-nong-dau-tu-moi-post371248.html -> mã KBC | Nhận diện "điểm nóng" đầu tư mới
✅ 18/06/2025 17:48 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-196-post371486.html -> mã CMG | Sự kiện chứng khoán đáng chú ý ngày 19/6
✅ 18/06/2025 17:44 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-196-post371490.html -> mã HSG | Cổ phiếu cần quan tâm ngày 19/6
✅ 18/06/2025 15:21 | https://www.tinnhanhchungkhoan.vn/sang-toi-buc-tranh-cong-bo-thong-tin-post371205.html -> mã MBB | Sáng, tối bức tranh công bố thông tin
✅ 18/06/2025 12:58 | https://www.tinnhanhchungkhoan.vn/ngan-hang-rot-rao-xu-ly-no-xau-post371336.html -> mã MBB | Ngân hàng rốt ráo xử lý nợ xấu
✅ 18/06/2025 07:06 | https://www.tinnhanhchungkhoan.vn/viconship-vsc-muon-ban-hon-63-trieu-co-phieu-cang-xanh-vip-vgr-post371412.html -> mã VSC | Viconship (VSC) muốn bán hơn 6,3 triệu cổ phiếu Cảng Xanh Vip (VGR)
✅ 18/06/2025 06:39 | https://www.tinnhanhchungkhoan.vn/co-phieu-chan-nuoi-tang-nhiet-post371291.html -> mã DBC | Cổ phiếu chăn nuôi "tăng nhiệt"
✅ 18/06/2025 06:36 | https://www.tinnhanhchungkhoan.vn/bien-tin-xau-thanh-co-hoi-post371237.html -> mã HSG | Biến tin xấu thành cơ hội
✅ 17/06/2025 17:44 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-186-post371408.html -> mã KBC, mã VCB | Cổ phiếu cần quan tâm ngày 18/6
✅ 17/06/2025 16:14 | https://www.tinnhanhchungkhoan.vn/chung-khoan-vndirect-vnd-chot-quyen-chia-co-tuc-5-bang-tien-mat-post371399.html -> mã VND | Chứng khoán VNDirect (VND) chốt quyền chia cổ tức 5% bằng tiền mặt
✅ 17/06/2025 15:33 | https://www.tinnhanhchungkhoan.vn/thi-truong-tai-san-ma-hoa-ky-vong-ve-mot-san-choi-cong-bang-va-minh-bach-post371242.html -> mã SSI | Thị trường tài sản mã hóa: Kỳ vọng về một "sân chơi" công bằng và minh bạch
✅ 17/06/2025 14:26 | https://www.tinnhanhchungkhoan.vn/nam-tan-uyen-ntc-nop-ho-so-niem-yet-gan-24-trieu-co-phieu-len-hose-post371381.html -> mã VCB | Nam Tân Uyên (NTC) nộp hồ sơ niêm yết gần 24 triệu cổ phiếu lên HOSE
✅ 17/06/2025 14:09 | https://www.tinnhanhchungkhoan.vn/viconship-vsc-de-cu-2-nhan-su-vao-hdqt-hai-an-hah-sau-khi-lien-tuc-nang-so-huu-post371377.html -> mã VSC | Viconship (VSC) đề cử 2 nhân sự vào HĐQT Hải An (HAH) sau khi liên tục nâng sở hữu
✅ 17/06/2025 07:43 | https://www.tinnhanhchungkhoan.vn/he-lo-ung-vien-do-ssj-consulting-vietnam-llc-de-xuat-tham-gia-hoi-dong-quan-tri-gemadept-gmd-post371343.html -> mã GMD | Hé lộ ứng viên do SSJ Consulting (Vietnam) LLC đề xuất tham gia Hội đồng quản trị Gemadept (GMD)
✅ 16/06/2025 18:16 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-176-post371320.html -> mã KDH, mã VND | Sự kiện chứng khoán đáng chú ý ngày 17/6
✅ 16/06/2025 14:13 | https://www.tinnhanhchungkhoan.vn/nhip-dieu-chinh-lanh-manh-post371289.html -> mã HPG | Nhịp điều chỉnh lành mạnh
✅ 16/06/2025 07:30 | https://www.tinnhanhchungkhoan.vn/sau-thep-nhom-den-luot-kinh-xay-dung-vao-tam-ngam-chong-ban-pha-gia-post371274.html -> mã HSG, mã NKG | Sau thép, nhôm, đến lượt kính xây dựng vào "tầm ngắm" chống bán phá giá
✅ 15/06/2025 17:40 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-166-post371178.html -> mã MBB | Cổ phiếu cần quan tâm ngày 16/6
✅ 14/06/2025 19:14 | https://www.tinnhanhchungkhoan.vn/mb-tang-mien-phi-ung-dung-mseller-giai-phap-ho-tro-ban-hang-va-phat-hanh-hoa-don-dien-tu-post371197.html -> mã MBB | MB tặng miễn phí ứng dụng mSeller - giải pháp hỗ trợ bán hàng và phát hành hóa đơn điện tử
✅ 14/06/2025 11:33 | https://www.tinnhanhchungkhoan.vn/coteccons-ctd-lap-cu-dup-tai-hubexo-asia-awards-2025-hai-nam-lien-tiep-nam-trong-top-10-nha-thau-hang-dau-viet-nam-post371173.html -> mã CTD | Coteccons (CTD) lập cú đúp tại Hubexo Asia Awards 2025: Hai năm liên tiếp nằm trong top 10 nhà thầu hàng đầu Việt Nam
✅ 13/06/2025 17:35 | https://www.tinnhanhchungkhoan.vn/bat-dong-san-chiem-mot-nua-trong-tong-gia-tri-trai-phieu-dao-han-nua-cuoi-nam-post371139.html -> mã MBB | Bất động sản chiếm một nửa trong tổng giá trị trái phiếu đáo hạn nửa cuối năm
✅ 13/06/2025 06:40 | https://www.tinnhanhchungkhoan.vn/fpt-tro-thanh-doi-tac-cong-nghe-chien-luoc-toan-cau-cua-airbus-post371102.html -> mã FPT | FPT trở thành Đối tác Công nghệ Chiến lược Toàn cầu của Airbus
✅ 12/06/2025 17:42 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-136-post371099.html -> mã HPG | Cổ phiếu cần quan tâm ngày 13/6
✅ 12/06/2025 15:25 | https://www.tinnhanhchungkhoan.vn/thanh-khoan-cai-thien-vn-index-hoi-phuc-len-tren-1320-diem-post371083.html -> mã VND | Thanh khoản cải thiện, VN-Index hồi phục lên trên 1.320 điểm
✅ 12/06/2025 11:34 | https://www.tinnhanhchungkhoan.vn/8-thang-hoa-sen-hsg-vuot-13-ke-hoach-loi-nhuan-nien-do-tai-chinh-2024-2025-post371062.html -> mã HSG | 8 tháng, Hoa Sen (HSG) vượt 13% kế hoạch lợi nhuận niên độ tài chính 2024-2025
✅ 11/06/2025 18:05 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-126-post371028.html -> mã KDH | Sự kiện chứng khoán đáng chú ý ngày 12/6
✅ 11/06/2025 15:48 | https://www.tinnhanhchungkhoan.vn/hsc-hcm-phat-hanh-them-gan-360-trieu-co-phieu-cho-co-dong-hien-huu-gia-10000-dongcp-post371021.html -> mã HCM | HSC (HCM) phát hành thêm gần 360 triệu cổ phiếu cho cổ đông hiện hữu, giá 10.000 đồng/CP
✅ 11/06/2025 09:23 | https://www.tinnhanhchungkhoan.vn/doanh-nghiep-thep-xoay-chuyen-giua-bao-thue-quan-post370998.html -> mã HSG, mã NKG | Doanh nghiệp thép xoay chuyển giữa bão thuế quan
✅ 11/06/2025 10:29 | https://www.tinnhanhchungkhoan.vn/loc-co-phieu-co-tin-tuc-bat-thuong-post370855.html -> mã VNM | Lọc cổ phiếu có tin tức "bất thường"
✅ 10/06/2025 19:09 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-116-post370981.html -> mã CTD, mã TLG | Sự kiện chứng khoán đáng chú ý ngày 11/6
✅ 10/06/2025 17:40 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-116-post370982.html -> mã PNJ, mã REE | Cổ phiếu cần quan tâm ngày 11/6
✅ 10/06/2025 12:59 | https://www.tinnhanhchungkhoan.vn/giao-dich-chung-khoan-thoi-cua-tien-tuoi-thoc-that-post370856.html -> mã BMP | Giao dịch chứng khoán: Thời của "tiền tươi, thóc thật"
✅ 10/06/2025 11:03 | https://www.tinnhanhchungkhoan.vn/agriseco-research-thi-truong-bat-dong-san-buoc-vao-chu-ky-phuc-hoi-moi-post370944.html -> mã KDH | Agriseco Research: Thị trường bất động sản bước vào chu kỳ phục hồi mới
✅ 10/06/2025 06:58 | https://www.tinnhanhchungkhoan.vn/dau-tu-thuong-mai-smc-smc-doi-tru-so-chinh-sau-thong-tin-ban-tru-so-cu-post370929.html -> mã NKG | Đầu tư Thương mại SMC (SMC) đổi trụ sở chính sau thông tin bán trụ sở cũ
✅ 10/06/2025 06:41 | https://www.tinnhanhchungkhoan.vn/dong-dem-tac-dong-voi-nganh-thep-tu-muc-thue-moi-post370861.html -> mã HPG, mã HSG, mã NKG | Đong đếm tác động với ngành thép từ mức thuế mới
✅ 09/06/2025 17:41 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-106-post370926.html -> mã BMP, mã VCB | Cổ phiếu cần quan tâm ngày 10/6
✅ 09/06/2025 17:16 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-106-post370925.html -> mã FPT, mã PDR, mã VIX | Sự kiện chứng khoán đáng chú ý ngày 10/6
✅ 09/06/2025 15:40 | https://www.tinnhanhchungkhoan.vn/gemadept-gmd-phan-dau-dat-2000-ty-dong-loi-nhuan-va-trinh-mua-lai-5-co-phan-lam-co-phieu-quy-post370910.html -> mã GMD | Gemadept (GMD) phấn đấu đạt 2.000 tỷ đồng lợi nhuận và trình mua lại 5% cổ phần làm cổ phiếu quỹ
✅ 09/06/2025 14:32 | https://www.tinnhanhchungkhoan.vn/chung-khoan-vix-vix-sap-phat-hanh-them-729-trieu-co-phieu-de-tra-co-tuc-post370901.html -> mã VIX | Chứng khoán VIX (VIX) sắp phát hành thêm 72,9 triệu cổ phiếu để trả cổ tức
✅ 09/06/2025 14:29 | https://www.tinnhanhchungkhoan.vn/ma-phuong-nam-pnc-thien-long-tlg-toan-tinh-gi-post370860.html -> mã TLG | M&A Phương Nam (PNC), Thiên Long (TLG) toan tính gì?
✅ 09/06/2025 12:58 | https://www.tinnhanhchungkhoan.vn/co-phieu-bat-dong-san-buoc-vao-chu-ky-tang-truong-moi-post370852.html -> mã KDH, mã PDR | Cổ phiếu bất động sản bước vào chu kỳ tăng trưởng mới
✅ 09/06/2025 10:23 | https://www.tinnhanhchungkhoan.vn/trien-vong-moi-trong-hop-tac-kinh-te-viet-nam-thuy-dien-post370880.html -> mã FPT | Triển vọng mới trong hợp tác kinh tế Việt Nam - Thụy Điển
✅ 06/06/2025 06:53 | https://www.tinnhanhchungkhoan.vn/dic-corp-dig-chuyen-nhuong-17-can-ho-du-an-cap-saint-jacques-giai-doan-1-cho-cong-ty-con-post370726.html -> mã DIG | DIC Corp (DIG) chuyển nhượng 17 căn hộ dự án Cap Saint Jacques - Giai đoạn 1 cho công ty con
✅ 06/06/2025 06:43 | https://www.tinnhanhchungkhoan.vn/agribank-tao-dung-nen-tang-vung-chac-giup-nguoi-tre-an-cu-lap-nghiep-post370720.html -> mã MBB | Agribank tạo dựng nền tảng vững chắc giúp người trẻ "an cư lập nghiệp"
✅ 05/06/2025 17:47 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-66-post370717.html -> mã FPT, mã REE | Cổ phiếu cần quan tâm ngày 6/6
✅ 05/06/2025 06:44 | https://www.tinnhanhchungkhoan.vn/co-phieu-bat-dong-san-co-nhieu-dong-luc-de-giai-nen-post370385.html -> mã VND | Cổ phiếu bất động sản có nhiều động lực để "giải nén"
✅ 04/06/2025 17:46 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-56-post370632.html -> mã KDH | Cổ phiếu cần quan tâm ngày 5/6
✅ 04/06/2025 17:37 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-56-post370633.html -> mã PTB | Sự kiện chứng khoán đáng chú ý ngày 5/6
✅ 04/06/2025 07:34 | https://www.tinnhanhchungkhoan.vn/viet-nam-gia-han-dieu-tra-thep-nhap-khau-tu-trung-quoc-han-quoc-post370580.html -> mã HSG, mã NKG | Việt Nam gia hạn điều tra thép nhập khẩu từ Trung Quốc, Hàn Quốc
✅ 04/06/2025 07:04 | https://www.tinnhanhchungkhoan.vn/mot-lanh-dao-pv-gas-gas-sap-tham-gia-vao-hdqt-pvtrans-pvt-post370565.html -> mã GAS | Một lãnh đạo PV GAS (GAS) sắp tham gia vào HĐQT PVTrans (PVT)
✅ 04/06/2025 06:43 | https://www.tinnhanhchungkhoan.vn/co-phieu-cang-bien-vung-vang-giua-bao-thue-quan-post370386.html -> mã GMD, mã VSC | Cổ phiếu cảng biển vững vàng giữa bão thuế quan
✅ 03/06/2025 18:14 | https://www.tinnhanhchungkhoan.vn/thi-truong-tai-chinh-24h-thoi-diem-nha-dau-tu-co-the-tai-co-cau-danh-muc-post370545.html -> mã VND | Thị trường tài chính 24h: Thời điểm nhà đầu tư có thể tái cơ cấu danh mục
✅ 03/06/2025 18:14 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-46-post370555.html -> mã ANV, mã HDG, mã VSC | Sự kiện chứng khoán đáng chú ý ngày 4/6
✅ 03/06/2025 17:16 | https://www.tinnhanhchungkhoan.vn/fpt-bat-tay-cymotive-thuc-day-doi-moi-an-ninh-mang-trong-nganh-cong-nghiep-o-to-post370558.html -> mã FPT | FPT "bắt tay" Cymotive, thúc đẩy đổi mới an ninh mạng trong ngành công nghiệp ô tô
✅ 04/06/2025 11:09 | https://www.tinnhanhchungkhoan.vn/quy-bmff-thi-truong-chung-khoan-viet-nam-dang-hap-dan-se-tan-dung-cac-nhip-dieu-chinh-de-mua-vao-post370552.html -> mã MBB | Quỹ BMFF: Thị trường chứng khoán Việt Nam đang hấp dẫn, sẽ tận dụng các nhịp điều chỉnh để mua vào
✅ 03/06/2025 15:27 | https://www.tinnhanhchungkhoan.vn/dong-tien-chay-manh-vn-index-tang-gan-11-diem-post370549.html -> mã HCM | Dòng tiền chảy mạnh, VN-Index tăng gần 11 điểm
✅ 03/06/2025 12:30 | https://www.tinnhanhchungkhoan.vn/vndirect-du-dia-tang-thi-truong-chung-khoan-thang-6-khong-lon-co-hoi-nam-o-nhom-chung-khoan-thep-xuat-khau-post370537.html -> mã VND | VNDirect: Dư địa tăng thị trường chứng khoán tháng 6 không lớn, cơ hội nằm ở nhóm chứng khoán, thép, xuất khẩu
✅ 03/06/2025 10:49 | https://www.tinnhanhchungkhoan.vn/hoa-phat-hpg-chot-quyen-chia-co-tuc-bang-co-phieu-ty-le-20-post370538.html -> mã HPG | Hòa Phát (HPG) chốt quyền chia cổ tức bằng cổ phiếu, tỷ lệ 20%
✅ 03/06/2025 10:37 | https://www.tinnhanhchungkhoan.vn/hai-phong-dinh-hinh-khong-gian-do-thi-moi-post370529.html -> mã VSC | Hải Phòng: Định hình không gian đô thị mới
✅ 03/06/2025 09:58 | https://www.tinnhanhchungkhoan.vn/co-phieu-duoc-chuyen-trang-thai-post370387.html -> mã IMP | Cổ phiếu dược chuyển trạng thái
✅ 02/06/2025 18:48 | https://www.tinnhanhchungkhoan.vn/su-kien-chung-khoan-dang-chu-y-ngay-36-post370485.html -> mã HPG | Sự kiện chứng khoán đáng chú ý ngày 3/6
✅ 02/06/2025 17:41 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-36-post370490.html -> mã GMD | Cổ phiếu cần quan tâm ngày 3/6
✅ 02/06/2025 11:45 | https://www.tinnhanhchungkhoan.vn/bsi-ngay-gdkhq-tra-co-tuc-nam-2024-bang-co-phieu-101-post370462.html -> mã BSI | BSI: Ngày GDKHQ trả cổ tức năm 2024 bằng cổ phiếu (10:1)
✅ 02/06/2025 11:35 | https://www.tinnhanhchungkhoan.vn/pgc-ngay-gdkhq-tra-co-tuc-nam-2024-bang-tien-11-post370445.html -> mã GAS | PGC: Ngày GDKHQ trả cổ tức năm 2024 bằng tiền (11%)
✅ 02/06/2025 07:41 | https://www.tinnhanhchungkhoan.vn/vn-index-chiu-ap-luc-dieu-chinh-bat-dong-san-buoc-vao-chu-ky-tang-truong-moi-post370384.html -> mã HPG | VN-Index chịu áp lực điều chỉnh, bất động sản bước vào chu kỳ tăng trưởng mới
✅ 02/06/2025 07:39 | https://www.tinnhanhchungkhoan.vn/vn-index-dang-duoc-dinh-gia-o-muc-hap-dan-post370383.html -> mã HPG | VN-Index đang được định giá ở mức hấp dẫn
✅ 01/06/2025 17:42 | https://www.tinnhanhchungkhoan.vn/co-phieu-can-quan-tam-ngay-26-post370345.html -> mã FPT | Cổ phiếu cần quan tâm ngày 2/6

KeyboardInterrupt:

# ***VIETSTOCK***

In [ ]:
def setup_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless=new")  # nếu muốn thấy trình duyệt, comment dòng này
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--window-size=1920,1080")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled")
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    chrome_options.add_experimental_option('useAutomationExtension', False)
    chrome_options.add_argument("--disable-extensions")
    # Chặn ảnh để nhanh/nhẹ
    chrome_options.add_experimental_option("prefs", {
        "profile.managed_default_content_settings.images": 2
    })

    driver = webdriver.Chrome(options=chrome_options)
    # Ẩn một số dấu hiệu automation
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": """
            Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
            Object.defineProperty(navigator, 'languages', { get: () => ['vi-VN','vi'] });
            Object.defineProperty(navigator, 'plugins', { get: () => [1,2,3] });
        """
    })
    return driver

# =========================
# HỖ TRỢ: tìm input & set value + bắn event
# =========================
def _find_clickable_css(driver, selectors, timeout=30):
    """Tìm element theo nhiều CSS, ưu tiên cái hiện & click được."""
    end = time.time() + timeout
    last_err = None
    while time.time() < end:
        for sel in selectors:
            try:
                el = driver.find_element(By.CSS_SELECTOR, sel)
                if el.is_displayed():
                    try:
                        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, sel)))
                    except Exception:
                        pass
                    return sel, el
            except Exception as e:
                last_err = e
        time.sleep(1)
    raise last_err or TimeoutException("Không tìm thấy input ngày")

def _robust_set_input(driver, el, value):
    """Set input: gỡ readonly, focus, Ctrl+A, delete, send_keys, rồi bắn events bằng JS."""
    driver.execute_script("arguments[0].removeAttribute('readonly');arguments[0].removeAttribute('disabled');", el)
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", el)
    try:
        el.click()
    except Exception:
        pass
    try:
        el.send_keys(Keys.CONTROL, 'a')
    except Exception:
        pass
    try:
        el.send_keys(Keys.DELETE)
    except Exception:
        pass
    try:
        el.send_keys(value)
    except Exception:
        # fallback set bằng JS
        driver.execute_script("arguments[0].value = arguments[1];", el, value)

    # bắn sự kiện để UI lib/datepicker bắt thay đổi
    driver.execute_script("""
        const el = arguments[0];
        el.dispatchEvent(new Event('input',  {bubbles:true}));
        el.dispatchEvent(new Event('change', {bubbles:true}));
        try {
          if (window.jQuery) {
            const $el = jQuery(el);
            if ($el.data && ($el.data('datepicker') || $el.data('DateTimePicker'))) {
              try { $el.datepicker && $el.datepicker('setDate', el.value); } catch(e) {}
              $el.trigger && $el.trigger('changeDate');
            }
          }
        } catch(e) {}
    """, el)

# =========================
# SET DATE FILTER (ĐÃ SỬA)
# =========================
def set_date_filter(driver, from_date, to_date):
    """
    - Tìm đúng input: #txtFromDate/#txtToDate bên trong .input-group.date
    - Gỡ readonly, set bằng send_keys + JS
    - Click 'Tìm kiếm'
    - Chờ #latest-news thay đổi nội dung
    """
    try:
        WebDriverWait(driver, 35).until(EC.presence_of_element_located((By.ID, "latest-news")))

        # Tìm input theo nhiều khả năng (theo DOM bạn gửi)
        from_css_list = [
            "#txtFromDate input.form-control",
            "#txtFromDate input",
            "input[name='FromDate']",
            "input#FromDate",
        ]
        to_css_list = [
            "#txtToDate input.form-control",
            "#txtToDate input",
            "input[name='ToDate']",
            "input#ToDate",
        ]

        from_sel, from_el = _find_clickable_css(driver, from_css_list, timeout=20)
        to_sel,   to_el   = _find_clickable_css(driver, to_css_list,   timeout=20)

        # HTML cũ để chờ thay đổi
        try:
            old_html = driver.find_element(By.ID, "latest-news").get_attribute("innerHTML")
        except Exception:
            old_html = None

        # Set giá trị vào 2 input
        _robust_set_input(driver, from_el, from_date)
        _robust_set_input(driver, to_el,   to_date)

        # Debug: in giá trị thực tế trong DOM sau khi set
        vals = driver.execute_script("""
            return {
              from_input: document.querySelector(arguments[0])?.value || null,
              to_input:   document.querySelector(arguments[1])?.value || null
            };
        """, from_sel, to_sel)
        print("Date values (after set):", vals)

        # Click 'Tìm kiếm'
        btn = WebDriverWait(driver, 30).until(EC.element_to_be_clickable((By.ID, "btn-news-filter")))
        try:
            btn.click()
        except Exception:
            driver.execute_script("arguments[0].click();", btn)

        # Chờ nội dung đổi
        if old_html is not None:
            WebDriverWait(driver, 35).until(
                lambda d: d.find_element(By.ID, "latest-news").get_attribute("innerHTML") != old_html
            )
        else:
            WebDriverWait(driver, 25).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "#latest-news tr"))
            )

        # In thử 3–5 ngày đầu để kiểm tra
        try:
            html = driver.find_element(By.ID, "latest-news").get_attribute("innerHTML")
            soup = BeautifulSoup(html, "html.parser")
            sample_dates = [td.get_text(strip=True) for td in soup.select("td.col-date")[:5]]
            print("Sample dates:", sample_dates)
        except Exception:
            pass

        return True

    except Exception as e:
        # In traceback cho dễ chẩn đoán
        try:
            import traceback
            print("Lỗi thiết lập bộ lọc chi tiết:\n", traceback.format_exc())
        except Exception:
            pass
        print(" Lỗi thiết lập bộ lọc:", getattr(e, "msg", str(e)))
        return False

# =========================
# GET TOTAL PAGES (giữ nguyên)
# =========================
def get_total_pages(driver):
    try:
        pagination = driver.find_element(By.ID, "latest-paging")
        page_links = pagination.find_elements(By.CSS_SELECTOR, "li a[page]")

        if page_links:
            pages = [int(link.get_attribute("page")) for link in page_links if link.get_attribute("page").isdigit()]
            return max(pages) if pages else 1
        return 1
    except Exception as e:
        print(f" Không thể lấy số trang: {e}")
        return 1

# =========================
# EXTRACT NEWS (giữ nguyên)
# =========================
def extract_news_from_page(driver, symbol):
    news_list = []
    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, "latest-news"))
        )

        soup = BeautifulSoup(driver.page_source, 'html.parser')
        news_table = soup.find('div', id='latest-news')

        if news_table:
            rows = news_table.find_all('tr')

            for row in rows:
                try:
                    date_cell = row.find('td', class_='col-date')
                    if not date_cell:
                        continue

                    date_str = date_cell.text.strip()

                    link_cell = row.find('a', class_='news-link')
                    if not link_cell:
                        continue

                    link = link_cell.get('href', '')
                    if link.startswith('//'):
                        link = 'https:' + link
                    elif link.startswith('/'):
                        link = 'https://vietstock.vn' + link

                    title_element = link_cell.find(string=True, recursive=False)
                    if not title_element:
                        title = link_cell.get_text(strip=True)
                    else:
                        title = title_element.strip()

                    if date_str and title and link:
                        news_list.append({
                            'Date': date_str,
                            'Symbol': symbol,
                            'Link': link,
                            'Title': title
                        })
                except Exception:
                    continue
    except Exception as e:
        print(f" Lỗi trích xuất tin tức: {e}")

    return news_list

# =========================
# AJAX PAGING (ĐÃ SỬA: dùng FromDate/ToDate)
# =========================
def crawl_page_with_ajax(driver, symbol, page_num, from_date, to_date):
    try:
        ajax_script = f"""
        (function() {{
          const container = document.querySelector('#latest-news');
          if (!container) return 'no_container';
          const oldHTML = container.innerHTML;

          const params = new URLSearchParams();
          params.append('view', '1');
          params.append('code', '{symbol}');
          params.append('type', '1');
          // Sử dụng PascalCase như nhiều payload trên site
          params.append('FromDate', '{from_date}');
          params.append('ToDate', '{to_date}');
          params.append('channelID', '1');
          params.append('page', '{page_num}');
          params.append('pageSize', '20');

          return fetch('/View/PagingNewsContent', {{
            method: 'POST',
            headers: {{ 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' }},
            body: params
          }}).then(r => r.text()).then(html => {{
            container.innerHTML = html;
            return 'ok';
          }});
        }})();
        """
        old_html = driver.find_element(By.ID, "latest-news").get_attribute("innerHTML")
        driver.execute_script(ajax_script)

        # Đợi nội dung đổi
        WebDriverWait(driver, 45).until(
            lambda d: d.find_element(By.ID, "latest-news").get_attribute("innerHTML") != old_html
        )
        return True
    except Exception as e:
        print(f"Lỗi AJAX trang {page_num}: {e}")
        return False

# =========================
# NAVIGATE PAGING (giữ nguyên)
# =========================
def navigate_to_page(driver, page_num):
    try:
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(1)

        page_link = WebDriverWait(driver, 45).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, f"#latest-paging a[page='{page_num}']"))
        )

        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", page_link)
        old_html = driver.find_element(By.ID, "latest-news").get_attribute("innerHTML")
        time.sleep(1.5)

        try:
            page_link.click()
        except Exception:
            driver.execute_script("arguments[0].click();", page_link)

        WebDriverWait(driver, 45).until(
            lambda d: d.find_element(By.ID, "latest-news").get_attribute("innerHTML") != old_html
        )
        return True
    except Exception as e:
        print(f" Không thể chuyển trang {page_num}: {e}")
        return False

# =========================
# CRAWLER (giữ nguyên luồng, dùng hàm đã sửa)
# =========================
def crawl_vietstock_news(symbols, from_date="01/01/2014", to_date="31/12/2024"):
    all_news = []
    driver = setup_driver()

    try:
        for symbol in symbols:
            print(f"\nCrawling: {symbol}")

            url = f"https://finance.vietstock.vn/{symbol}/tin-moi-nhat.htm"
            driver.get(url)
            WebDriverWait(driver, 45).until(
                EC.presence_of_element_located((By.ID, "latest-news"))
            )

            if not set_date_filter(driver, from_date, to_date):
                print(f" Không thể thiết lập bộ lọc cho {symbol}")
                continue

            total_pages = get_total_pages(driver)
            print(f"📄 Tổng số trang: {total_pages}")

            symbol_news_count = 0

            for page in range(1, total_pages + 1):
                if page > 1:
                    if not crawl_page_with_ajax(driver, symbol, page, from_date, to_date):
                        if not navigate_to_page(driver, page):
                            continue

                news_data = extract_news_from_page(driver, symbol)
                page_count = len(news_data)
                symbol_news_count += page_count

                print(f"   Trang {page}: {page_count} bài")

                all_news.extend(news_data)
                time.sleep(1)  # nghỉ nhẹ tránh bị chặn

            print(f" {symbol}: {symbol_news_count} bài tổng cộng")

    except Exception as e:
        print(f"Lỗi crawl: {e}")
    finally:
        driver.quit()

    return all_news

# =========================
# SAVE EXCEL (giữ nguyên)
# =========================
def save_to_excel(news_data, filename="vietstock_news.xlsx"):
    if not news_data:
        print(" Không có dữ liệu để lưu")
        return

    try:
        df = pd.DataFrame(news_data)
        df['Date_parsed'] = pd.to_datetime(df['Date'], format='%d/%m/%Y', errors='coerce')
        df = df.sort_values(['Symbol', 'Date_parsed'], ascending=[True, False])
        df = df.drop('Date_parsed', axis=1)

        df.to_excel(filename, index=False, engine='openpyxl')
        print(f"\nĐã lưu {len(df)} bài báo → {filename}")

        print("\nThống kê:")
        for symbol in df['Symbol'].unique():
            count = len(df[df['Symbol'] == symbol])
            print(f"   {symbol}: {count} bài")
    except Exception as e:
        print(f"Lỗi lưu file: {e}")

# =========================
# MAIN (giữ nguyên)
# =========================
def main():
    symbols = ['BMP', 'BSI']
    from_date = "01/01/2014"
    to_date = "31/12/2024"

    print("VIETSTOCK NEWS CRAWLER")
    print(f"Mã: {', '.join(symbols)}")
    print(f"Thời gian: {from_date} → {to_date}")
    print()

    news_data = crawl_vietstock_news(symbols, from_date, to_date)

    if news_data:
        save_to_excel(news_data, "vietstock_news_dbc_ctd.xlsx")
        print(f" Hoàn thành! Tổng cộng: {len(news_data)} bài báo")
    else:
        print("Không có dữ liệu")

if __name__ == "__main__":
    main()

VIETSTOCK NEWS CRAWLER
Mã: BMP, BSI
Thời gian: 01/01/2014 → 31/12/2024


Crawling: BMP
Date values (after set): {'from_input': '01/01/2014', 'to_input': '31/12/2024'}
Sample dates: ['23/12/2024', '04/12/2024', '14/11/2024', '22/10/2024', '18/10/2024']
📄 Tổng số trang: 29
   Trang 1: 20 bài
   Trang 2: 20 bài
   Trang 3: 20 bài
   Trang 4: 20 bài
   Trang 5: 20 bài
   Trang 6: 20 bài
   Trang 7: 0 bài
   Trang 8: 20 bài
   Trang 9: 20 bài
   Trang 10: 20 bài
   Trang 11: 20 bài
   Trang 12: 20 bài
   Trang 13: 20 bài
   Trang 14: 20 bài
   Trang 15: 20 bài
   Trang 16: 20 bài
   Trang 17: 20 bài
   Trang 18: 20 bài
   Trang 19: 20 bài
   Trang 20: 20 bài
   Trang 21: 20 bài
   Trang 22: 20 bài
   Trang 23: 20 bài
   Trang 24: 20 bài
   Trang 25: 20 bài
   Trang 26: 20 bài
   Trang 27: 20 bài
   Trang 28: 20 bài
   Trang 29: 15 bài
 BMP: 555 bài tổng cộng

Crawling: BSI
Date values (after set): {'from_input': '01/01/2014', 'to_input': '31/12/2024'}
Sample dates: ['30/12/2024', '30/12/2024', '18/12/2024', '18/12/2024', '18/12/2024']
📄 Tổng số trang: 38
   Trang 1: 20 bài
   Trang 2: 20 bài
   Trang 3: 20 bài
   Trang 4: 20 bài
   Trang 5: 20 bài
   Trang 6: 20 bài
   Trang 7: 20 bài
   Trang 8: 20 bài
   Trang 9: 20 bài
   Trang 10: 20 bài
   Trang 11: 20 bài
   Trang 12: 20 bài
   Trang 13: 20 bài
   Trang 14: 20 bài
   Trang 15: 20 bài
   Trang 16: 20 bài
   Trang 17: 20 bài
   Trang 18: 20 bài
   Trang 19: 20 bài
   Trang 20: 20 bài
   Trang 21: 20 bài
   Trang 22: 20 bài
   Trang 23: 20 bài
   Trang 24: 20 bài
   Trang 25: 20 bài
   Trang 26: 20 bài
   Trang 27: 20 bài
   Trang 28: 20 bài
   Trang 29: 20 bài
   Trang 30: 20 bài
   Trang 31: 20 bài
   Trang 32: 20 bài
   Trang 33: 20 bài
   Trang 34: 20 bài
   Trang 35: 20 bài
   Trang 36: 20 bài
   Trang 37: 20 bài
   Trang 38: 13 bài
 BSI: 753 bài tổng cộng

Đã lưu 1308 bài báo → vietstock_news_dbc_ctd.xlsx

Thống kê:
   BMP: 555 bài
   BSI: 753 bài
 Hoàn thành! Tổng cộng: 1308 bài báo

In [ ]:
# Tải lại excel để để crawl nội dung pHead
from google.colab import files
uploaded = files.upload()
excel_path = list(uploaded.keys())[0]
df = pd.read_excel(excel_path)
df

Saving vietstock_news_bmp_bsi.xlsx to vietstock_news_bmp_bsi.xlsx

,Date,Symbol,Link,Title
0,23/12/2024,BMP,https://vietstock.vn/2024/12/phan-tich-ky-thua...,Phân tích kỹ thuật phiên chiều 23/12: Tình hìn...
1,04/12/2024,BMP,https://vietstock.vn/2024/12/phan-tich-ky-thua...,Phân tích kỹ thuật phiên chiều 04/12: Tiếp diễ...
2,14/11/2024,BMP,https://vietstock.vn/2024/11/theo-dau-dong-tie...,Theo dấu dòng tiền cá mập 14/11: Khối ngoại ti...
3,22/10/2024,BMP,https://vietstock.vn/2024/10/nhua-binh-minh-sa...,Nhựa Bình Minh sắp chi gần 500 tỷ tạm ứng cổ t...
4,18/10/2024,BMP,https://vietstock.vn/2024/10/bmp-nghi-quyet-hd...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...
...,...,...,...,...
1303,11/02/2014,BSI,https://vietstock.vn/2014/02/chung-khoan-bsi-t...,Chứng khoán BSI: Thị trường tháng 2 sẽ dao độn...
1304,08/02/2014,BSI,https://vietstock.vn/2014/02/bsi-bao-cao-tinh-...,BSI: Báo cáo tình hình quản trị công ty 2013
1305,17/01/2014,BSI,https://vietstock.vn/2014/01/bsi-ttck-2014-tan...,BSI: TTCK 2014 tăng điểm chậm nhưng chắc
1306,16/01/2014,BSI,https://vietstock.vn/2014/01/bsi-bao-cao-tinh-...,BSI: Báo cáo tình hình quản trị công ty 2013
1307,15/01/2014,BSI,https://vietstock.vn/2014/01/bsi-quy-4-lai-6-t...,"BSI: Quý 4 lãi 6 tỷ đồng, cả năm gấp 5 lần kế ..."

In [ ]:
# đặt BASE_DOMAIN phù hợp ở đây (đoán điển hình là Vietstock).
BASE_DOMAIN = "https://vietstock.vn"   # nếu link đã là tuyệt đối (http...), dòng này không ảnh hưởng

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123 Safari/537.36"
})

def normalize_url(url: str) -> str:
    """Chuẩn hóa URL: nhận tuyệt đối, thêm domain nếu là tương đối."""
    if not isinstance(url, str):
        return ""
    u = url.strip()
    if not u:
        return ""
    if u.startswith("http://") or u.startswith("https://"):
        return u
    if u.startswith("//"):
        return "https:" + u
    if u.startswith("/"):
        return urljoin(BASE_DOMAIN, u)
    # trường hợp như "vie/abc..." hoặc "vietstock.vn/..."
    if re.match(r"^[a-zA-Z0-9]+/.*", u):
        return urljoin(BASE_DOMAIN, "/" + u)
    if u.startswith("www."):
        return "https://" + u
    return u  # để nguyên nếu không đoán được

def fetch_phead(url: str, max_retries: int = 3, timeout: int = 20) -> str:
    """Tải trang và trích đoạn <p class='pHead'>; trả về chuỗi rỗng nếu thất bại."""
    u = normalize_url(url)
    if not u:
        return ""

    for attempt in range(1, max_retries + 1):
        try:
            resp = session.get(u, timeout=timeout, allow_redirects=True)
            # Một số trang chặn non-200 bằng JS; vẫn thử parse nếu có HTML
            if resp.status_code >= 500:
                raise requests.HTTPError(f"Server error {resp.status_code}")
            html = resp.text
            soup = BeautifulSoup(html, "lxml")

            # tìm <p class="pHead">
            node = soup.select_one("p.pHead")
            if node:
                text = node.get_text(" ", strip=True)
                if text:
                    return text

            # fallback: thử thêm các biến thể thường gặp
            fallback = soup.find("p", class_=re.compile(r"phead|pHead", re.I))
            if fallback:
                text = fallback.get_text(" ", strip=True)
                if text:
                    return text

            # thêm 1 fallback cuối: meta description
            meta = soup.find("meta", attrs={"name": "description"})
            if meta and meta.get("content"):
                return meta["content"].strip()

            return ""
        except Exception as e:
            # backoff nhẹ
            if attempt < max_retries:
                time.sleep(1.5 * attempt)
            else:
                return ""

# Đảm bảo có cột Link/Title
if "Link" not in df.columns or "Title" not in df.columns:
    raise ValueError("File Excel cần có cột 'Link' và 'Title'.")

# Crawl với progress bar
pheads = []
for url in tqdm(df["Link"].tolist(), desc="Crawling pHead"):
    pheads.append(fetch_phead(url))

df["pHead"] = pheads

# Tạo cột content = Title + ". " + pHead (nếu pHead rỗng vẫn tạo)
df["Title"] = df["Title"].fillna("").astype(str).str.strip()
df["pHead"] = df["pHead"].fillna("").astype(str).str.strip()
df["content"] = df.apply(lambda r: (r["Title"] + (". " if r["Title"] and r["pHead"] else ".") + r["pHead"]).strip(), axis=1)

df.head(10)

Crawling pHead: 100%|██████████| 1308/1308 [26:28<00:00,  1.21s/it]

,Date,Symbol,Link,Title,pHead,content
0,23/12/2024,BMP,https://vietstock.vn/2024/12/phan-tich-ky-thua...,Phân tích kỹ thuật phiên chiều 23/12: Tình hìn...,VN-Index và HNX-Index đồng loạt tăng điểm cùng...,Phân tích kỹ thuật phiên chiều 23/12: Tình hìn...
1,04/12/2024,BMP,https://vietstock.vn/2024/12/phan-tich-ky-thua...,Phân tích kỹ thuật phiên chiều 04/12: Tiếp diễ...,VN-Index và HNX-Index tăng giảm trái chiều đồn...,Phân tích kỹ thuật phiên chiều 04/12: Tiếp diễ...
2,14/11/2024,BMP,https://vietstock.vn/2024/11/theo-dau-dong-tie...,Theo dấu dòng tiền cá mập 14/11: Khối ngoại ti...,Trong bối cảnh VN-Index chốt phiên 14/11 mất h...,Theo dấu dòng tiền cá mập 14/11: Khối ngoại ti...
3,22/10/2024,BMP,https://vietstock.vn/2024/10/nhua-binh-minh-sa...,Nhựa Bình Minh sắp chi gần 500 tỷ tạm ứng cổ t...,Với việc sở hữu số dư tiền nhàn rỗi kỷ lục gần...,Nhựa Bình Minh sắp chi gần 500 tỷ tạm ứng cổ t...
4,18/10/2024,BMP,https://vietstock.vn/2024/10/bmp-nghi-quyet-hd...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...
5,18/10/2024,BMP,https://vietstock.vn/2024/10/bmp-nghi-quyet-hd...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...,BMP: Nghị quyết HĐQT về việc tạm ứng cổ tức ti...
6,18/10/2024,BMP,https://vietstock.vn/2024/10/nhua-binh-minh-la...,"Nhựa Bình Minh lại tạo kỷ lục mới, giá cổ phiế...",Lãi gộp quý 3/2024 của CTCP Nhựa Bình Minh ( H...,"Nhựa Bình Minh lại tạo kỷ lục mới, giá cổ phiế..."
7,16/10/2024,BMP,https://vietstock.vn/2024/10/phan-tich-ky-thua...,Phân tích kỹ thuật phiên chiều 16/10: Tiếp diễ...,VN-Index và HNX-Index tăng giảm trái chiều cùn...,Phân tích kỹ thuật phiên chiều 16/10: Tiếp diễ...
8,16/10/2024,BMP,https://vietstock.vn/2024/10/bmp-bctc-quy-3-na...,BMP: BCTC quý 3 năm 2024,BMP: BCTC quý 3 năm 2024,BMP: BCTC quý 3 năm 2024. BMP: BCTC quý 3 năm ...
9,16/10/2024,BMP,https://vietstock.vn/2024/10/bmp-bctc-hop-nhat...,BMP: BCTC Hợp nhất quý 3 năm 2024,BMP: BCTC Hợp nhất quý 3 năm 2024,BMP: BCTC Hợp nhất quý 3 năm 2024. BMP: BCTC H...

In [ ]:
out_xlsx = "output_with_content.xlsx"
df.to_excel(out_xlsx, index=False)

# ***CAFEF***

In [ ]:
import pandas as pd
import time
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from bs4 import BeautifulSoup

vn30_symbols = ["PDR"]
url_template = "https://cafef.vn/du-lieu/tin-doanh-nghiep/{symbol}/event.chn"

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=chrome_options)

def is_date_in_range(date_obj):
    start_date = datetime(2025, 6, 30)
    end_date = datetime(2025, 1, 1)
    return start_date <= date_obj <= end_date

articles_list = []

# Thu thập danh sách bài báo từ tất cả các trang
for symbol in vn30_symbols:
    url = url_template.format(symbol=symbol.lower())
    print(f"\nĐang xử lý: {symbol} ({url})")
    try:
        driver.get(url)
        time.sleep(7)
        page_count = 1
        last_page_content = None
        while True:
            soup = BeautifulSoup(driver.page_source, "html.parser")
            news_container = soup.find("div", class_="tintucsukien")
            if not news_container:
                print(f"Không tìm thấy tintucsukien cho {symbol}")
                break
            events_div = news_container.find("div", id="divEvents")
            if not events_div:
                print(f"Không tìm thấy divEvents cho {symbol}")
                break
            articles = events_div.find_all("li")
            print(f"Trang {page_count}: {len(articles)} bài báo")
            if len(articles) == 0:
                print(f"Không còn bài báo trên trang {page_count} cho {symbol}")
                break
            for article in articles:
                title_tag = article.find("a", class_="docnhanhTitle")
                if not title_tag:
                    continue
                title = title_tag.get_text(strip=True)
                link = "https://cafef.vn" + title_tag["href"] if not title_tag["href"].startswith("http") else title_tag["href"]
                date_tag = article.find("span", class_="timeTitle")
                if not date_tag:
                    continue
                date_str = date_tag.get_text(strip=True)
                try:
                    datetime_obj = datetime.strptime(date_str, "%d/%m/%Y %H:%M")
                    articles_list.append({"Symbol": symbol, "Title": title, "Link": link, "Date": datetime_obj})
                except ValueError as e:
                    print(f"Trang {page_count}: Lỗi định dạng ngày {date_str} - {e}")
                    continue
            current_page_content = driver.page_source
            try:
                next_button = driver.find_element(By.ID, "aNext")
                driver.execute_script("LoadNext();")
                time.sleep(2)
                new_page_content = driver.page_source
                if new_page_content == current_page_content or new_page_content == last_page_content:
                    print(f"Không có nội dung mới trên trang {page_count + 1} cho {symbol}")
                    break
                last_page_content = current_page_content
                page_count += 1
            except (NoSuchElementException, TimeoutException):
                print(f"Đã hết trang cho {symbol}")
                break
    except Exception as e:
        print(f"Lỗi khi xử lý {symbol}: {e}")
        continue

# Xử lý chi tiết từng bài báo (chỉ lấy tóm tắt)
data = []
for item in articles_list:
    try:
        if is_date_in_range(item["Date"]):
            driver.get(item["Link"])
            time.sleep(3)
            detail_soup = BeautifulSoup(driver.page_source, "html.parser")
            # Lấy tóm tắt từ h2 class="sapo"
            summary_h2 = detail_soup.find("h2", class_="sapo")
            content = summary_h2.get_text(strip=True) if summary_h2 else "N/A"
            print(f"Thêm {item['Title']} (ngày: {item['Date']}, tóm tắt: {content[:50]}...)")
            data.append({
                "Date": item["Date"],
                "Symbol": item["Symbol"],
                "Title": item["Title"],
                "Link": item["Link"],
                "Content": content
            })
    except Exception as e:
        print(f"Lỗi khi xử lý {item['Title']}: {e}")
        continue

driver.quit()

df = pd.DataFrame(data, columns=["Date", "Symbol", "Title", "Link", "Content"])
output_file = "cafef_vn30_news.xlsx"
df.to_excel(output_file, index=False, engine="openpyxl")
print(f"\nDữ liệu lưu tại {output_file}")
print(f"Tổng cộng: {len(data)} bài báo")
if df.empty:
    print("Cảnh báo: File trống, kiểm tra log")
else:
    print("DataFrame mẫu:")
    print(df.head())

Đang xử lý: PDR (https://cafef.vn/du-lieu/tin-doanh-nghiep/pdr/event.chn)
Trang 1: 30 bài báo
Trang 2: 30 bài báo
Trang 3: 30 bài báo
Trang 4: 30 bài báo
Trang 5: 30 bài báo
Trang 6: 30 bài báo
Trang 7: 30 bài báo
Trang 8: 30 bài báo
Trang 9: 30 bài báo
Trang 10: 30 bài báo
Trang 11: 30 bài báo
Trang 12: 30 bài báo
Trang 13: 30 bài báo
Trang 14: 30 bài báo
Trang 15: 30 bài báo
Trang 16: 30 bài báo
Trang 17: 30 bài báo
Trang 18: 30 bài báo
Trang 19: 30 bài báo
Trang 20: 30 bài báo
Trang 21: 30 bài báo
Trang 22: 30 bài báo
Trang 23: 30 bài báo
Trang 24: 30 bài báo
Trang 25: 30 bài báo
Trang 26: 30 bài báo
Trang 27: 30 bài báo
Trang 28: 30 bài báo
Trang 29: 30 bài báo
Trang 30: 30 bài báo
Trang 31: 30 bài báo
Trang 32: 30 bài báo
Trang 33: 30 bài báo
Trang 34: 30 bài báo
Trang 35: 30 bài báo
Trang 36: 30 bài báo
Trang 37: 30 bài báo
Trang 38: 30 bài báo
Trang 39: 30 bài báo
Trang 40: 30 bài báo
Trang 41: 30 bài báo
Trang 42: 30 bài báo
Trang 43: 30 bài báo
Trang 44: 30 bài báo
Trang 45: 0 bài báo
Không còn bài báo trên trang 45 cho PDR

Dữ liệu lưu tại cafef_vn30_news.xlsx
Tổng cộng: 0 bài báo
Cảnh báo: File trống, kiểm tra log

In [ ]:
vn30_symbols = ["PDR"]
url_template = "https://cafef.vn/du-lieu/tin-doanh-nghiep/{symbol}/event.chn"

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=chrome_options)

def is_date_in_range(date_obj):
    """Kiểm tra ngày có trong khoảng từ 1/1/2025 đến 30/6/2025"""
    start_date = datetime(2025, 1, 1)
    end_date = datetime(2025, 6, 30)
    return start_date <= date_obj <= end_date

def parse_date_flexible(date_str):
    """Xử lý parsing ngày với nhiều định dạng khác nhau"""
    # Loại bỏ khoảng trắng thừa
    date_str = date_str.strip()

    # Các định dạng có thể có
    formats = [
        "%d/%m/%Y %H:%M",
        "%d/%m/%Y",
        "%d.%m.%Y",
        "%d-%m-%Y %H:%M",
        "%d-%m-%Y"
    ]

    for fmt in formats:
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            continue

    # Nếu không parse được, thử extract số
    try:
        # Tìm pattern dd/mm/yyyy hoặc dd.mm.yyyy
        date_match = re.search(r'(\d{1,2})[./](\d{1,2})[./](\d{4})', date_str)
        if date_match:
            day, month, year = map(int, date_match.groups())

            # Validate ngày tháng
            if month > 12:
                day, month = month, day  # Đổi chỗ nếu tháng > 12

            # Kiểm tra ngày hợp lệ
            try:
                return datetime(year, month, day)
            except ValueError:
                # Nếu ngày không hợp lệ, thử điều chỉnh
                if day > 31:
                    day = 31 if month in [1,3,5,7,8,10,12] else 30
                elif day > 30 and month in [4,6,9,11]:
                    day = 30
                elif day > 28 and month == 2:
                    day = 29 if year % 4 == 0 else 28

                return datetime(year, month, day)
    except:
        pass

    raise ValueError(f"Không thể parse ngày: {date_str}")

articles_list = []

# Thu thập danh sách bài báo từ tất cả các trang
for symbol in vn30_symbols:
    url = url_template.format(symbol=symbol.lower())
    print(f"\nĐang xử lý: {symbol} ({url})")
    try:
        driver.get(url)
        time.sleep(7)
        page_count = 1
        last_page_content = None

        while True:
            soup = BeautifulSoup(driver.page_source, "html.parser")
            news_container = soup.find("div", class_="tintucsukien")
            if not news_container:
                print(f"Không tìm thấy tintucsukien cho {symbol}")
                break

            events_div = news_container.find("div", id="divEvents")
            if not events_div:
                print(f"Không tìm thấy divEvents cho {symbol}")
                break

            articles = events_div.find_all("li")
            print(f"Trang {page_count}: {len(articles)} bài báo")

            if len(articles) == 0:
                print(f"Không còn bài báo trên trang {page_count} cho {symbol}")
                break

            for article in articles:
                title_tag = article.find("a", class_="docnhanhTitle")
                if not title_tag:
                    continue

                title = title_tag.get_text(strip=True)
                link = "https://cafef.vn" + title_tag["href"] if not title_tag["href"].startswith("http") else title_tag["href"]

                date_tag = article.find("span", class_="timeTitle")
                if not date_tag:
                    continue

                date_str = date_tag.get_text(strip=True)
                try:
                    datetime_obj = parse_date_flexible(date_str)
                    articles_list.append({
                        "Symbol": symbol,
                        "Title": title,
                        "Link": link,
                        "Date": datetime_obj
                    })
                except ValueError as e:
                    print(f"Trang {page_count}: Lỗi định dạng ngày '{date_str}' - {e}")
                    continue

            current_page_content = driver.page_source
            try:
                next_button = driver.find_element(By.ID, "aNext")
                driver.execute_script("LoadNext();")
                time.sleep(2)
                new_page_content = driver.page_source

                if new_page_content == current_page_content or new_page_content == last_page_content:
                    print(f"Không có nội dung mới trên trang {page_count + 1} cho {symbol}")
                    break

                last_page_content = current_page_content
                page_count += 1

            except (NoSuchElementException, TimeoutException):
                print(f"Đã hết trang cho {symbol}")
                break

    except Exception as e:
        print(f"Lỗi khi xử lý {symbol}: {e}")
        continue

print(f"\nTổng số bài báo thu thập: {len(articles_list)}")

# Xử lý chi tiết từng bài báo (chỉ lấy tóm tắt)
data = []
processed_count = 0

for item in articles_list:
    try:
        if is_date_in_range(item["Date"]):
            print(f"Đang xử lý: {item['Title']} ({item['Date'].strftime('%d/%m/%Y')})")
            driver.get(item["Link"])
            time.sleep(3)

            detail_soup = BeautifulSoup(driver.page_source, "html.parser")

            # Lấy tóm tắt từ h2 class="sapo"
            summary_h2 = detail_soup.find("h2", class_="sapo")
            content = summary_h2.get_text(strip=True) if summary_h2 else "N/A"

            data.append({
                "Date": item["Date"],
                "Symbol": item["Symbol"],
                "Title": item["Title"],
                "Link": item["Link"],
                "Content": content
            })

            processed_count += 1
            print(f"✓ Đã xử lý ({processed_count}/{len([x for x in articles_list if is_date_in_range(x['Date'])])})")
        else:
            print(f"Bỏ qua bài ngoài khoảng thời gian: {item['Title']} ({item['Date'].strftime('%d/%m/%Y')})")

    except Exception as e:
        print(f"Lỗi khi xử lý '{item['Title']}': {e}")
        continue

driver.quit()

# Lưu dữ liệu
df = pd.DataFrame(data, columns=["Date", "Symbol", "Title", "Link", "Content"])
output_file = "cafef_vn30_news.xlsx"

try:
    df.to_excel(output_file, index=False, engine="openpyxl")
    print(f"\n✓ Dữ liệu đã lưu tại {output_file}")
    print(f"✓ Tổng cộng: {len(data)} bài báo trong khoảng thời gian 01/01/2025 - 30/06/2025")

    if not df.empty:
        print("\nDataFrame mẫu:")
        print(df.head())
        print(f"\nThống kê theo ngày:")
        print(df['Date'].dt.strftime('%Y-%m').value_counts().sort_index())
    else:
        print("⚠️ Cảnh báo: File trống, kiểm tra khoảng thời gian và dữ liệu")

except Exception as e:
    print(f"Lỗi khi lưu file: {e}")

Đang xử lý: PDR (https://cafef.vn/du-lieu/tin-doanh-nghiep/pdr/event.chn)
Trang 1: 30 bài báo
Trang 2: 30 bài báo
Trang 3: 30 bài báo
Trang 4: 30 bài báo
Trang 5: 30 bài báo
Trang 6: 30 bài báo
Trang 7: 30 bài báo
Trang 8: 30 bài báo
Trang 9: 30 bài báo
Trang 10: 30 bài báo
Trang 11: 30 bài báo
Trang 12: 30 bài báo
Trang 13: 30 bài báo
Trang 14: 30 bài báo
Trang 15: 30 bài báo
Trang 16: 30 bài báo
Trang 17: 30 bài báo
Trang 18: 30 bài báo
Trang 19: 30 bài báo
Trang 20: 30 bài báo
Trang 21: 30 bài báo
Trang 22: 30 bài báo
Trang 23: 30 bài báo
Trang 24: 30 bài báo
Trang 25: 30 bài báo
Trang 26: 30 bài báo
Trang 27: 30 bài báo
Trang 28: 30 bài báo
Trang 29: 30 bài báo
Trang 30: 30 bài báo
Trang 31: 30 bài báo
Trang 32: 30 bài báo
Trang 33: 30 bài báo
Trang 34: 30 bài báo
Trang 35: 30 bài báo
Trang 36: 30 bài báo
Trang 37: 30 bài báo
Trang 38: 30 bài báo
Trang 39: 30 bài báo
Trang 40: 30 bài báo
Trang 41: 30 bài báo
Trang 42: 30 bài báo
Trang 43: 30 bài báo
Trang 44: 24 bài báo
Trang 45: 0 bài báo
Không còn bài báo trên trang 45 cho PDR

Tổng số bài báo thu thập: 1314
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt báo lãi 65 tỷ khi doanh thu 20 tỷ: "Phép màu" từ một giao dịch và đối tác bí ẩn thành lập đúng ngày ký thương vụ (21/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Giấy chứng nhận đăng ký doanh nghiệp thay đổi lần thứ 39 (21/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Sửa đổi, bổ sung Điều lệ công ty (21/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: 26.8.2025, giao dịch 72.574.296 cp niêm yết bổ sung (19/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: 19.8.2025, niêm yết bổ sung 72.574.296 cp (18/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Đính chính nội dung báo cáo kết quả đợt phát hành cổ phiếu để trả cổ tức (15/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: CBTT thay đổi vốn điều lệ và sửa đổi điều lệ công ty (14/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo nhận được công văn của UBCKNN về tài liệu báo cáo kết quả phát hành cổ phiếu để trả cổ tức (13/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Số lượng cổ phiếu có quyền biểu quyết đang lưu hành là 979.809.379 cp (11/08/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Đã phát hành 72.574.296 cổ phiếu để trả cổ tức (11/08/2025)
Bỏ qua bài ngoài khoảng thời gian: Công bố Top 20 công ty bất động sản tư nhân nộp ngân sách lớn nhất Việt Nam (04/08/2025)
Bỏ qua bài ngoài khoảng thời gian: Gọi tên 10 DN bất động sản báo lãi tăng mạnh nhất sàn chứng khoán quý 2/2025, có công ty tăng đến 4.009% (02/08/2025)
Bỏ qua bài ngoài khoảng thời gian: Doanh thu tăng 141% so với cùng kỳ, Phát Đạt báo lãi quý 2/2025 tăng 30%, đạt 65 tỷ đồng (31/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Giải trình KQKD quý 2/2025 so với cùng kỳ năm trước (31/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: 4.8.2025, ngày GDKHQ trả cổ tức bằng cổ phiếu (tỷ lệ 100:8) (30/07/2025)
Bỏ qua bài ngoài khoảng thời gian: Dự án của Phát Đạt, Đại Quang Minh, DIC, Investco, Hưng Lộc Phát... nằm trong diện bị thanh tra (29/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Báo cáo tình hình quản trị 6 tháng đầu năm 2025 (29/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo ngày ĐKCC để thực hiện quyền nhận cổ tức bằng cổ phiếu cho cổ đông hiện hữu (24/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo về việc nhận được công văn của UBCKNN về tài liệu báo cáo phát hành cổ phiếu để trả cổ tức (24/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo ký hợp đồng kiểm toán BCTC 2025 (18/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT triển khai phương án phát hành và hồ sơ phát hành cổ phiếu để trả cho CĐHH (16/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đã bán 3.397.652 cp (14/07/2025)
Bỏ qua bài ngoài khoảng thời gian: PDR: Đính chính nội dung Bản sửa đổi điều lệ công ty (03/07/2025)
Đang xử lý: PDR: Bản sửa đổi Điều lệ công ty, Quy chế nội bộ về quản trị công ty, Quy chế hoạt động của HĐQT (30/06/2025)
✓ Đã xử lý (1/63)
Đang xử lý: PDR: Bổ nhiệm ông Vũ Thành Lê giữ chức Thành viên độc lập HĐQT từ 27.6.2025 (30/06/2025)
✓ Đã xử lý (2/63)
Đang xử lý: PDR: Biên bản họp và Nghị quyết ĐHĐCĐ thường niên năm 2025 (30/06/2025)
✓ Đã xử lý (3/63)
Đang xử lý: Chủ tịch Phát Đạt: Sau khi sáp nhập hai địa phương Bà Rịa - Vũng Tàu và Bình Dương vào TP.HCM, tổng quỹ đất của công ty gần 1.000 ha (28/06/2025)
✓ Đã xử lý (4/63)
Đang xử lý: Phát Đạt muốn bán công ty con ngàn tỉ ở Bình Định (23/06/2025)
✓ Đã xử lý (5/63)
Đang xử lý: PDR: Báo cáo tiến độ sử dụng vốn từ đợt chào bán (23/06/2025)
✓ Đã xử lý (6/63)
Đang xử lý: PDR: CBTT chuyển nhượng toàn bộ cổ phần tại công ty con (20/06/2025)
✓ Đã xử lý (7/63)
Đang xử lý: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đăng ký bán 3.397.652 cp (09/06/2025)
✓ Đã xử lý (8/63)
Đang xử lý: Con trai Chủ tịch Phát Đạt (PDR) muốn bán sạch 3,4 triệu cổ phiếu (08/06/2025)
✓ Đã xử lý (9/63)
Đang xử lý: PDR: Đính chính một số nội dung của Báo cáo tình hình quản trị công ty năm 2023, bổ sung một số QĐ HĐQT năm 2021, 2023 (29/05/2025)
✓ Đã xử lý (10/63)
Đang xử lý: PDR: CBTT triển khai tổ chức họp ĐHĐCĐ thường niên 2025 (29/05/2025)
✓ Đã xử lý (11/63)
Đang xử lý: PDR: 16.4.2026, giao dịch 34.095.000 cp niêm yết bổ sung (23/05/2025)
✓ Đã xử lý (12/63)
Đang xử lý: PDR: 23.5.2025, niêm yết bổ sung 34.095.000 cp (22/05/2025)
✓ Đã xử lý (13/63)
Đang xử lý: PDR: Cải chính thông tin liên quan đến chỉ tiêu lợi nhuận sau thuế thu nhập doanh nghiệp (08/05/2025)
✓ Đã xử lý (14/63)
Đang xử lý: PDR: Cải chính thông tin liên quan đến chỉ tiêu lợi nhuận sau thuế thu nhập doanh nghiệp (08/05/2025)
✓ Đã xử lý (15/63)
Đang xử lý: PDR: Giấy chứng nhận đăng ký doanh nghiệp thay đổi lần thứ 38 (05/05/2025)
✓ Đã xử lý (16/63)
Đang xử lý: Phát Đạt (PDR) bị phạt gần nửa tỷ đồng vì hàng loạt vi phạm trong công bố thông tin và sử dụng vốn trái phiếu (01/05/2025)
✓ Đã xử lý (17/63)
Đang xử lý: PDR: 19.5.2025, ngày GDKHQ tham dự ĐHCĐ thường niên năm 2025 (29/04/2025)
✓ Đã xử lý (18/63)
Đang xử lý: PDR: Quyết định của HĐQT về việc chốt ngày ĐKCC để thực hiện quyền tham dự ĐHĐCĐ thường niên 2025 (28/04/2025)
✓ Đã xử lý (19/63)
Đang xử lý: PDR: Bổ nhiệm lại ông Bùi Quang Anh Vũ giữ chức Tổng giám đốc (28/04/2025)
✓ Đã xử lý (20/63)
Đang xử lý: Phát Đạt (PDR): Doanh thu quý 1/2025 gấp 2,7 lần cùng kỳ nhưng lợi nhuận giảm, đã phát hành 34,1 triệu cp để hoán đổi nợ (25/04/2025)
✓ Đã xử lý (21/63)
Đang xử lý: PDR: Thông báo công văn của UBCKNN về tài liệu báo cáo phát hành cổ phiếu để hoán đổi nợ của PDR (24/04/2025)
✓ Đã xử lý (22/63)
Đang xử lý: PDR: Sửa đổi, bổ sung Điều lệ công ty (24/04/2025)
✓ Đã xử lý (23/63)
Đang xử lý: PDR: Quyết định của HĐQT thông qua việc thay đổi vốn điều lệ Công ty (24/04/2025)
✓ Đã xử lý (24/63)
Đang xử lý: PDR: Đính chính một số nội dung trong Báo cáo tình hình quản trị Công ty năm 2024 (24/04/2025)
✓ Đã xử lý (25/63)
Đang xử lý: PDR: Giải trình KQKD BCTC riêng quý 1/2025 so với cùng kỳ năm trước (23/04/2025)
✓ Đã xử lý (26/63)
Đang xử lý: PDR: Báo cáo thường niên năm 2024 (21/04/2025)
✓ Đã xử lý (27/63)
Đang xử lý: PDR: Số lượng cổ phiếu có quyền biểu quyết đang lưu hành là 907.235.083 cp (21/04/2025)
✓ Đã xử lý (28/63)
Đang xử lý: PDR: Đã phát hành 34.095.000 cổ phiếu để hoán đổi nợ (21/04/2025)
✓ Đã xử lý (29/63)
Đang xử lý: PDR: CBTT thông qua kết quả phân phối cổ phiếu phát hành để hoán đổi nợ (17/04/2025)
✓ Đã xử lý (30/63)
Đang xử lý: PDR: Thông báo nhận được công văn của UBCKNN về hồ sơ đăng ký phát hành cổ phiếu để hoán đổi nợ (16/04/2025)
✓ Đã xử lý (31/63)
Đang xử lý: PDR: Công ty TNHH Phát Đạt Holdings đã bán 880.000 cp (11/04/2025)
✓ Đã xử lý (32/63)
Đang xử lý: PDR: Ông Nguyễn Văn Đạt - Chủ tịch HĐQT đã bán 1.620.000 cp (11/04/2025)
✓ Đã xử lý (33/63)
Đang xử lý: Chủ tịch HĐQT Phát Đạt bị call margin hàng triệu cổ phiếu (10/04/2025)
✓ Đã xử lý (34/63)
Đang xử lý: PDR: Giải trình KQKD năm 2024 sau kiểm toán so với cùng kỳ năm trước (04/04/2025)
✓ Đã xử lý (35/63)
Đang xử lý: PDR: Giải trình chênh lệch KQKD năm 2024 trước và sau kiểm toán (04/04/2025)
✓ Đã xử lý (36/63)
Đang xử lý: PDR: Nhắc nhở chậm nộp BCTC kiểm toán năm 2024 (02/04/2025)
✓ Đã xử lý (37/63)
Đang xử lý: PDR: Quyết định của HĐQT gia hạn thời gian tổ chức ĐHĐCĐ thường niên năm 2025 (01/04/2025)
✓ Đã xử lý (38/63)
Đang xử lý: Người từng là "tay hòm chìa khóa" của Phát Đạt thao túng cổ phiếu PDR? (24/03/2025)
✓ Đã xử lý (39/63)
Đang xử lý: PDR: Ông Lê Quang Phúc - thành viên HĐQT đã bán 240.000 cp (14/03/2025)
✓ Đã xử lý (40/63)
Đang xử lý: Phát Đạt điều chỉnh giảm doanh thu, lợi nhuận năm 2024, sẽ triển khai loạt dự án bất động sản trọng điểm trong năm 2025 (11/03/2025)
✓ Đã xử lý (41/63)
Đang xử lý: PDR: CBTT thông qua chủ trương điều chỉnh doanh thu, lợi nhuận sau thuế năm 2024 (11/03/2025)
✓ Đã xử lý (42/63)
Đang xử lý: Chủ tịch Phát Đạt: Dự kiến sẽ thu đủ khoản nợ 1.000 tỷ đồng từ Danh Khôi trong 6-12 tháng tới, sắp mua thêm 1-2 dự án trong quý II (01/03/2025)
✓ Đã xử lý (43/63)
Đang xử lý: PDR: Đính chính một số nội dung Báo cáo tình hình quản trị công ty năm 2024 (20/02/2025)
✓ Đã xử lý (44/63)
Đang xử lý: PDR: Ông Lê Quang Phúc - thành viên HĐQT đăng ký bán 240.000 cp (18/02/2025)
✓ Đã xử lý (45/63)
Đang xử lý: Loạt sếp doanh nghiệp bất động sản nhận thù lao tiền tỷ năm 2024 (09/02/2025)
✓ Đã xử lý (46/63)
Đang xử lý: PDR: Ông Trương Ngọc Dũng - Phó Tổng giám đốc đã bán 62.097 cp (03/02/2025)
✓ Đã xử lý (47/63)
Đang xử lý: Phát Đạt bất ngờ báo doanh thu quý 4/2024 cao gấp 27 lần, dự án Quy Nhơn Iconic "mang tiền về cho mẹ" (24/01/2025)
✓ Đã xử lý (48/63)
Đang xử lý: PDR: Ông Nguyễn Khắc Sinh - Phó Tổng giám đốc đã bán 57.898 cp (24/01/2025)
✓ Đã xử lý (49/63)
Đang xử lý: PDR: Đơn xin từ nhiệm của ông Phan Lê Hòa - Phó Tổng giám đốc (24/01/2025)
✓ Đã xử lý (50/63)
Đang xử lý: PDR: Ông Phan Lê Hòa - Phó Tổng giám đốc từ nhiệm từ 24.1.2025 (24/01/2025)
✓ Đã xử lý (51/63)
Đang xử lý: PDR: Giải trình KQKD HN quý 4/2024 so với cùng kỳ năm trước (24/01/2025)
✓ Đã xử lý (52/63)
Đang xử lý: PDR: Báo cáo tình hình quản trị Công ty năm 2024 (24/01/2025)
✓ Đã xử lý (53/63)
Đang xử lý: Phát Đạt (PDR) vừa bổ nhiệm thêm 2 Phó Tổng giám đốc (23/01/2025)
✓ Đã xử lý (54/63)
Đang xử lý: PDR: Bổ nhiệm ông Nguyễn Hữu giữ chức Phó Tổng giám đốc từ 22.1.2025 (22/01/2025)
✓ Đã xử lý (55/63)
Đang xử lý: PDR: Thông báo thay đổi nhân sự - bổ nhiệm Ông Nguyễn Hữu (22/01/2025)
✓ Đã xử lý (56/63)
Đang xử lý: PDR: Bổ nhiệm bà Đặng Việt Tú Uyên giữ chức Phó Tổng giám đốc từ 22.1.2025 (22/01/2025)
✓ Đã xử lý (57/63)
Đang xử lý: Tổng Giám đốc Phát Đạt đã bán sạch cổ phiếu PDR (20/01/2025)
✓ Đã xử lý (58/63)
Đang xử lý: PDR: Ông Bùi Quang Anh Vũ - Tổng giám đốc đã bán 1.436.526 cp (20/01/2025)
✓ Đã xử lý (59/63)
Đang xử lý: PDR: Thông qua tiêu chí và phương pháp đánh giá hiệu quả hoạt động của HĐQT, thành viên HĐQT của Công ty năm 2025 (14/01/2025)
✓ Đã xử lý (60/63)
Đang xử lý: PDR: Quyết định của HĐQT số 01/2025 ngày 13/01/2025 (13/01/2025)
✓ Đã xử lý (61/63)
Đang xử lý: Phát Đạt (PDR) lên tiếng về việc nhiều lãnh đạo bán cổ phiếu, khẳng định là giao dịch bình thường, phục vụ nhu cầu cá nhân (08/01/2025)
✓ Đã xử lý (62/63)
Đang xử lý: PDR: Thông báo giao dịch cổ phiếu của Người nội bộ Trương Ngọc Dũng, Nguyễn Khắc Sinh, Bùi Quang Anh Vũ (06/01/2025)
✓ Đã xử lý (63/63)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt dự chi tối đa 650 tỷ đồng mua khu đất của một cá nhân (22/12/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Nghị quyết HĐQT thông qua chủ trương đồng ý mua tài sản (20/12/2024)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt (PDR) đã chi hơn 1.100 tỷ đồng cho 5 dự án (18/12/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Báo cáo tiến độ sử dụng vốn thu được từ đợt chào bán (18/12/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Nghị quyết HĐQT thông qua giao dịch vay tiền giữa Công ty với các bên liên quan (02/12/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT về việc dùng tài sản của công ty để đảm bảo cho khoản vay của công ty con (24/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT thông qua hồ sơ phát hành cổ phiếu để hoán đổi nợ (21/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Miễn nhiệm bà Lê Trần Bích Thùy - Phó Tổng Giám đốc từ 15.10.2024 (15/10/2024)
Bỏ qua bài ngoài khoảng thời gian: Loạt DN thép, BĐS, dệt may, bảo hiểm báo KQKD Q3/2024: Hòa Phát giữ doanh thu trên 30.000 tỷ, doanh thu Phát Đạt hơn 2 tỷ nhưng lãi 51 tỷ (12/10/2024)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt (PDR) công bố BCTC quý 3/2024: Lãi sau thuế đạt 51 tỷ đồng, dự án Bắc Hà Thanh có diễn biến mới (11/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Giải trình KQKD HN và Cty mẹ quý 3/2024 so với cùng kỳ năm trước (11/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Đính chính về việc thay đổi nội dung Nghị quyết HĐQT số 23/024 ngày 30/09/2024 (02/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT về việc điều chỉnh điều kiện khoản vay nước ngoài chuyển đổi (01/10/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Nghị quyết HĐQT thông qua chính sách tri ân khách hàng là cổ đông Công ty (30/09/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Miễn nhiệm bà Ngô Thúy Vân - Kế toán trưởng từ 26.9.2024 (26/09/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Bổ nhiệm bà Trần Thị Thùy Trang giữ chức Kế toán trưởng từ 26.9.2024 (26/09/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT đã bán 1.086.819 cp (25/09/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đã bán 617.754 cp (23/09/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT đăng ký bán 1.086.819 cp (30/08/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đăng ký bán 617.754 cp (30/08/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Giải trình chênh lệch lợi nhuận sau thuế 6 tháng đầu năm 2024 so với 6 tháng đầu năm 2023 (29/08/2024)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt tạm dừng trả cổ tức, ưu tiên phát hành cổ phiếu hoán đổi nợ (25/08/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT về việc tạm dừng triển khai phương án phát hành CP trả cổ tức và hủy QĐ số 18 (23/08/2024)
Bỏ qua bài ngoài khoảng thời gian: Chủ tịch Phát Đạt báo tin vui cho cổ đông: "Công ty mới được giao thêm đất dự án Bắc Hà Thanh, chứng tỏ PDR không có vi phạm đất đai trên 63 tỉnh, thành" (16/08/2024)
Bỏ qua bài ngoài khoảng thời gian: Các đại gia bất động sản TP HCM trả lương nhân viên thế nào? (05/08/2024)
Bỏ qua bài ngoài khoảng thời gian: Con gái Chủ tịch HĐQT Phát Đạt "quay xe" không bán cổ phiếu PDR như đăng ký (22/07/2024)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt (PDR): Doanh thu quý 2/2024 chỉ hơn 8 tỷ đồng, “cứu” lợi nhuận nhờ bán công ty liên kết cho “người quen cũ” (19/07/2024)
Bỏ qua bài ngoài khoảng thời gian: TTCK lên xuống nhộn nhịp nhưng có những cổ đông của nhiều công ty “chưa 1 lần vui” khi cổ phiếu liên tục dò đáy, giảm đến 81% từ đầu năm (19/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Giải trình biến động kết quả kinh doanh quý 2/2024 so với quý 2/2023 (19/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT chưa bán cp (19/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT chưa bán cp (18/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Báo cáo tình hình quản trị Công ty 06 tháng đầu năm 2024 (16/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo về việc giao dịch cổ phiếu thay đổi đăng ký niêm yết (10/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: 9.7.2024, niêm yết bổ sung 134.329.243 cp (05/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Nghị quyết HĐQT về việc triển khai phương án phát hành cổ phiếu để trả cổ tức (05/07/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Bản sửa đổi Điều lệ công ty (25/06/2024)
Bỏ qua bài ngoài khoảng thời gian: Phát Đạt sắp thu về tối thiểu hơn 1.400 tỷ đồng nhờ thoái vốn một công ty liên kết (24/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo ký kết hợp đồng kiểm toán BCTC 2024 (24/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Thông báo chủ trương chuyển nhượng cổ phần tại Công ty liên kết (21/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: CBTT nhận được công văn của UBCK về báo cáo kết quả chào bán cổ phiếu ra công chúng (19/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT đăng ký bán 1.086.819 cp (18/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Báo cáo kết quả giao dịch cổ phiếu của người nội bộ Nguyễn Đình Trí, Trương Ngọc Dũng (18/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Số lượng cổ phiếu có quyền biểu quyết đang lưu hành là 873.140.083 cp (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Đã phát hành 134.329.243 cp ra công chúng (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Khắc Sinh - Phó Tổng giám đốc đã mua 100.000 cp (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Bà Ngô Thúy Vân - Kế toán trưởng đã mua 270.000 cp (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Phan Lê Hòa - Phó Tổng giám đốc đã mua 100.000 cp (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đăng ký bán 617.754 cp (14/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Quyết định của HĐQT thông qua kết quả chào bán cổ phiếu cho CĐHH và phưng án xử lý cổ phiếu chưa phân phối hết (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Trương Ngọc Dũng - Phó Tổng giám đốc đăng ký mua 100.000 cp (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Phan Lê Hòa - Phó Tổng giám đốc đăng ký mua 100.000 cp (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Khắc Sinh - Phó Tổng giám đốc đăng ký mua 100.000 cp (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Đình Trí - Phó Tổng giám đốc đăng ký mua 100.000 cp (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Bà Ngô Thúy Vân - Kế toán trưởng đăng ký mua 270.000 cp (12/06/2024)
Bỏ qua bài ngoài khoảng thời gian: Chủ tịch Phát Đạt và bên liên quan “rộn ràng” chi hàng trăm tỷ mua đợt phát hành 134 triệu cổ phiếu giá 10.000 đồng (07/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT đã mua 1.086.819 cp (06/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Tấn Danh - Phó chủ tịch HĐQT đã mua 617.754 cp (06/06/2024)
Bỏ qua bài ngoài khoảng thời gian: Chủ tịch Phát Đạt cùng công ty liên quan vừa chi hơn 600 tỷ mua cổ phiếu PDR (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Công ty TNHH Phát Đạt Holdings đã mua 12.291.266 cp (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Văn Đạt - Chủ tịch HĐQT đã mua 51.496.689 cp (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Trương Ngọc Dũng - Phó Tổng giám đốc đã mua 9.553 cp (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Mẹ ông Trần Trọng Gia Vinh - Thành viên HĐQT đã mua 5.654 cp (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Bùi Quang Anh Vũ - Tổng giám đốc đã mua 221.003 cp (04/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Khắc Sinh - Phó Tổng giám đốc đã mua 9.487 cp (03/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Ông Nguyễn Đình Trí - Phó Tổng giám đốc đã mua 19.825 cp (03/06/2024)
Bỏ qua bài ngoài khoảng thời gian: Rót gần 100 tỷ vào dự án “đất vàng” nhà thi đấu Phan Đình Phùng, Phát Đạt xin được làm tiếp nhưng bất thành: Sẽ được trả lại bao nhiêu tiền? (02/06/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Bà Ngô Thúy Vân - Kế toán trưởng đã mua 58.856 cp (31/05/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Công đoàn cơ sở PDR đã mua 26.615 cp (31/05/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Con ông Nguyễn Văn Đạt - Chủ tịch HĐQT đăng ký mua 1.086.819 cp (29/05/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Công đoàn Cơ sở CTCP Phát triển Bất động sản Phát Đạt đăng ký mua 26.615 cp (28/05/2024)
Bỏ qua bài ngoài khoảng thời gian: PDR: Mẹ ông Trần Trọng Gia Vinh - Thành viên HĐQT đăng ký mua 5.654 cp (27/05/2024)